### ISSUE TITLE
Issue with paths and imports

### ISSUE THREAD

**Issue by jgeurts** [electronjs/electron-compile#24]
I'm having troubles importing jsx files using es6 style import statements. I have a sample application that reproduces the problem available at https://github.com/jgeurts/electron-es6

Please let me know what additional information I can provide. Thanks!

**Comment by jgeurts** [comment]
I should add that this is happening in Windows

**Comment by paulcbetts** [comment]
Why are you using all of this gulp nonsense? The whole point of electron-compile is that you *don't* use any of these things, it Just Works

**Comment by paulcbetts** [comment]
Aha, so I've found your problem, this is a tricky aspect of how Electron and node.js's module system play together that I've had to fight with myself a fair amount. 

So, from the node.js perspective, your Main Module is `static/index.html` - this means that, when you `require` anything with a relative path, it's going to be relative to this file. So far, so good!  The problem is in your static/index.html:

`<script src="../src/renderer/app.jsx"></script>`

This *works*, but script tags don't create a separate *node.js* module context, it just acts like a browser. So, from a node perspective, your root is still `static`, but `app.jsx` assumes that the root is `src/renderer` (because it should be!), so all its requires fail. 

To solve this, electron-compile actually includes a special element just for this, `x-require` - change your script tag to read like this:

`<x-require src="../src/renderer/app.jsx"></x-require>`

And everything will Just Work.
