### ISSUE TITLE
couldn't find the preset

### ISSUE THREAD

**Issue by lazywei** [electronjs/electron-compile#62]
Hi,

I follow the README such as creating a new entry file `./src/es6-init.js`. However, when I run `npm start` I got this error message:
```
App threw an error when running [Error: Couldn't find preset "stage-0" relative to directory "/Users/lazywei/Code/squirrel-square-js/src"]
```

Did I miss any thing?

**Comment by lazywei** [comment]
Add the `.babelrc` to specify
```
{
  "presets": ["es2015"]
}
```
and install the `babel-preset-es2015` package resolve this problem.

**Comment by DomVinyard** [comment]
This solved the same error for me. Should this not be included in the readme?

**Comment by christoth** [comment]
I had the same problem, when I tried to run a test app without any presets. 
It should be in the docs or ideally have a default for babel as well.

@paulcbetts I can create a PR to add this to the docs if you like.

**Comment by MarshallOfSound** [comment]
@christoth @DomVinyard 

Personally I don't feel this should be included in the README.  I'm reasonably sure this is a side effect of the difference between NPM 2.x and NPM 3.x.

In `3.x` and above NPM flattens modules so that the top level application (in this case your electron app) can technically use deep dependencies of it's dependencies.  In this case it wants to use the `stage-0` preset module from inside the `electron-compile` module.

In `3.x` this will work while in `2.x` this won't.  It's actually almost an issue with how `babel` resolves plugins and resets (it resolves relative to `cwd` not `__dirname`)

FWIW though you shouldn't need to add the `babelrc` file, you should only need to install `babel-preset-es2015` in your module so babel can resolve it correctly
